[tool.poetry]
name = "bearing-only-tracking"
version = "0.0.1"
description = ""
authors = ["gigafiga21"]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
matplotlib = "^3.4.2"
numpy = "^1.20.3"
scipy = "^1.6.3"
